// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjI7X4f_bVim1UYYj_QF3MjQZ0dC0Umig',
    appId: '1:861214877995:web:1f723a9ab0f81419eebd6e',
    messagingSenderId: '861214877995',
    projectId: 'weather-ai-c7d98',
    authDomain: 'weather-ai-c7d98.firebaseapp.com',
    storageBucket: 'weather-ai-c7d98.firebasestorage.app',
    measurementId: 'G-54D953PLQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiSQSHieQ0A6Gk-vt_wRpBXu6_NO0hoNo',
    appId: '1:861214877995:android:3710892e58e9c117eebd6e',
    messagingSenderId: '861214877995',
    projectId: 'weather-ai-c7d98',
    storageBucket: 'weather-ai-c7d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6kwiez7nXUP9-vJZ8zsx4McG0R4qS3o',
    appId: '1:861214877995:ios:d7b95e53bdea12c5eebd6e',
    messagingSenderId: '861214877995',
    projectId: 'weather-ai-c7d98',
    storageBucket: 'weather-ai-c7d98.firebasestorage.app',
    iosBundleId: 'com.example.weatherAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP6kwiez7nXUP9-vJZ8zsx4McG0R4qS3o',
    appId: '1:861214877995:ios:d7b95e53bdea12c5eebd6e',
    messagingSenderId: '861214877995',
    projectId: 'weather-ai-c7d98',
    storageBucket: 'weather-ai-c7d98.firebasestorage.app',
    iosBundleId: 'com.example.weatherAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjI7X4f_bVim1UYYj_QF3MjQZ0dC0Umig',
    appId: '1:861214877995:web:d1bc543988eab9fdeebd6e',
    messagingSenderId: '861214877995',
    projectId: 'weather-ai-c7d98',
    authDomain: 'weather-ai-c7d98.firebaseapp.com',
    storageBucket: 'weather-ai-c7d98.firebasestorage.app',
    measurementId: 'G-FSCWJ1VSV9',
  );
}
